### ISSUE TITLE
Wrong handling of scalar predicates

### ISSUE THREAD

**Issue by hyunsikjeong** [google/binja-hexagon#10]
In Hexagon, when a predicate register is used as a scalar value, the LSB of the register is used to show true/false. This can be confirmed by testing with hexagon-sim or QEMU.

Consider the following instruction packet which is randomly generated:
```
{
    R6|=asl(R3,#28u5)
    if (P3) R7=zxth(R8)
    if (!P1) R0=sxtb(R6)
    if (P0) R8=sxth(R1)
}
```

It is converted to the LLIL code:
```
temp6.d = R6
temp6.d = temp6.d | R3 << 0x1c
if (P3) then 3 else 5
temp7.d = R8 & ((1 << 0x10) - 1)
goto 5
if (not.b(P1)) then 6 else 8
temp0.d = ((R6 & ((1 << 8) - 1)) ^ 0x1 << (8 - 1)) - (1 << (8 - 1))
goto 8
if (P0) then 9 else 11
temp8.d = ((R1 & ((1 << 0x10) - 1)) ^ 0x1 << (0x10 - 1)) - (1 << (0x10 - 1))
goto 11
R8 = temp8.d
R0 = temp0.d
R7 = temp7.d
R6 = temp6.d
```

In the code, `if (P3)`, `if (not.b(P1))` and `if (P0)` show that it is not considering the LSB.
I assume this bug is from the old version of QEMU, as it has the same bug.

**Comment by cfircohen** [comment]
Thanks for raising this issue. Looks like this was the qemu fix? https://github.com/qemu/qemu/commit/07c0f65385b9

**Comment by hyunsikjeong** [comment]
I almost forgot the old QEMU bug I mentioned here (sorry, I have not been watching Hexagon-related tools for like 2-3yrs), but it seems you found the right one.
