### ISSUE TITLE
Broken build on 3.4.4149-dev

### ISSUE THREAD

**Issue by brinlyau** [google/binja-hexagon#13]
Undefined symbols for architecture arm64:
  "_BNMergeUserAnalysis", referenced from:
      BinaryNinja::FileMetadata::MergeUserAnalysis(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::function<bool (unsigned long, unsigned long)> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >) in libbinaryninjaapi.a(filemetadata.cpp.o)

BNMergeUserAnalysis is [gone](https://github.com/Vector35/binaryninja-api/commit/086435bd364505f7e05c8a83e48e8b5bec30c94d) in latest API. 

Needs to be replaced.

**Comment by brinlyau** [comment]
Ok, it was my fault, the API submodule needs to be updated (conflict with my bninja core lib being too new)

**Comment by CarloMara** [comment]
Confirm suggested fix works

**Comment by cfircohen** [comment]
Thanks for raising this issue. I recently accepted a PR to update the API submodule, and successfully tested the plugin on v.3.5. Please re-open if you're still seeing issues.
