### ISSUE TITLE
decode_jmp_buf is not thread safe

### ISSUE THREAD

**Issue by droptopx** [google/binja-hexagon#17]
decode_jmp_buf doesn't seem to be thread safe and is shared by threads. This would mean that if thread 1 attempts to use it to perform a longjmp and thread 2 sets it to a value it will use before thread 1 can perform this jump, thread 1 will start using thread 2's stack. This causes a lot of crashes on macOS due to the buffer being used to temporarily save x30 before sigprocmask is called internally in setjmp, which then gets restored and validated with a autibsp:

```
setjmp @ libsystem_platform.dylib:
->  0x188a83b24: pacibsp 
    0x188a83b28: stp    x21, x30, [x0]
    0x188a83b2c: mov    x21, x0
    0x188a83b30: orr    w0, wzr, #0x1
    0x188a83b34: mov    x1, #0x0
    0x188a83b38: add    x2, x21, #0xb0
    0x188a83b3c: bl     0x188a885f8               ; symbol stub for: sigprocmask
    0x188a83b40: mov    x0, x21
    0x188a83b44: ldp    x21, x30, [x0]
    0x188a83b48: autibsp
    0x188a83b4c: eor    x16, x30, x30, lsl #1
    0x188a83b50: tbz    x16, #0x3e, 0x188a83a54   ; _setjmp
```

 If another thread writes to the buffer during the time of register save & restore, a wrong value will find its way into x30 and autibsp will crash the process. If _setjmp and _longjmp are used instead, skipping the register save & restore at the cost of not saving the signal mask, the crashes seemingly stop [^1].  I am not sure what the reason for this is.

Potential fixes are:
1. Mark decode_jmp_buf with a portable thread local storage key word
2. Use the pthreads API for TLS (slower than compile-time support)
3. Forego the usage of setjmp/longjmp

[^1] I do have one crash which doesn't happen in setjmp which I wasn't able to reproduce but I think it might be related to the non-thread safety of decode_jmp_buf.

**Comment by cfircohen** [comment]
Thanks for raising this issue! PTAL https://github.com/google/binja-hexagon/commit/ef39429387f75d2a79480c6ce6961b027ca31e2a LMK if you stop seeing crashes with the patch.

**Comment by droptopx** [comment]
Thank you for taking a look at this so quickly! Apologies if I'm wrong about this, but isn't a significant portion of the run-time of the plugin spent in DecodePacket? Wouldn't a lock slow down the plugin quite a bit? Or was a lock supposed to be here anyway as the code called from DecodePacket is supposed to be run serially?

**Comment by cfircohen** [comment]
Yes, it might impact load wall time, but at this point it's more important for me not to crash :) I can look into a better ASSERT implementation later (likely C++ try/catch).

**Comment by cfircohen** [comment]
Thanks for the suggestion. I pushed a fix with the `__thread` declarative. Please re-open if you're still seeing issues.

**Comment by droptopx** [comment]
Thanks for pushing the fix.
