### ISSUE TITLE
link error while compiling plugin on osx 

### ISSUE THREAD

**Issue by hyperchem** [google/binja-hexagon#9]
here is the log output. it seems for some reason, binaryninja exported api did not compiled properly.  

[ 92%] Linking CXX shared library libarch_hexagon.dylib
Undefined symbols for architecture x86_64:
  "_BNAreArgumentRegistersUsedForVarArgs", referenced from:
      BinaryNinja::CoreCallingConvention::AreArgumentRegistersUsedForVarArgs() in libbinaryninjaapi.a(callingconvention.cpp.o)
  "_BNCreateStructureFromOffsetAccess", referenced from:
      BinaryNinja::BinaryView::CreateStructureFromOffsetAccess(BinaryNinja::QualifiedName const&, bool*) const in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNCreateStructureMemberFromAccess", referenced from:
      BinaryNinja::BinaryView::CreateStructureMemberFromAccess(BinaryNinja::QualifiedName const&, unsigned long long) const in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNCreateWideCharType", referenced from:
      BinaryNinja::Type::WideCharType(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libbinaryninjaapi.a(type.cpp.o)
  "_BNCreateWideCharTypeBuilder", referenced from:
      BinaryNinja::TypeBuilder::WideCharType(unsigned long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in libbinaryninjaapi.a(type.cpp.o)
  "_BNFindAllConstantWithProgress", referenced from:
      BinaryNinja::BinaryView::FindAllConstant(unsigned long long, unsigned long long, unsigned long long, BinaryNinja::Ref<BinaryNinja::DisassemblySettings>, BNFunctionGraphType, std::__1::function<bool (unsigned long, unsigned long)> const&, std::__1::function<bool (unsigned long long, BinaryNinja::LinearDisassemblyLine const&)> const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFindAllDataWithProgress", referenced from:
      BinaryNinja::BinaryView::FindAllData(unsigned long long, unsigned long long, BinaryNinja::DataBuffer const&, BNFindFlag, std::__1::function<bool (unsigned long, unsigned long)> const&, std::__1::function<bool (unsigned long long, BinaryNinja::DataBuffer const&)> const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFindAllTextWithProgress", referenced from:
      BinaryNinja::BinaryView::FindAllText(unsigned long long, unsigned long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, BinaryNinja::Ref<BinaryNinja::DisassemblySettings>, BNFindFlag, BNFunctionGraphType, std::__1::function<bool (unsigned long, unsigned long)> const&, std::__1::function<bool (unsigned long long, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, BinaryNinja::LinearDisassemblyLine const&)> const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFreeTypeFieldReferenceSizeInfo", referenced from:
      BinaryNinja::BinaryView::GetAllSizesReferenced(BinaryNinja::QualifiedName const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFreeTypeFieldReferenceSizes", referenced from:
      BinaryNinja::BinaryView::GetSizesReferenced(BinaryNinja::QualifiedName const&, unsigned long long) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFreeTypeFieldReferenceTypeInfo", referenced from:
      BinaryNinja::BinaryView::GetAllTypesReferenced(BinaryNinja::QualifiedName const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFreeTypeFieldReferenceTypes", referenced from:
      BinaryNinja::BinaryView::GetTypesReferenced(BinaryNinja::QualifiedName const&, unsigned long long) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNFreeTypeFieldReferences", referenced from:
      BinaryNinja::BinaryView::GetCodeReferencesForTypeField(BinaryNinja::QualifiedName const&, unsigned long long) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNGetAllFieldsReferenced", referenced from:
      BinaryNinja::BinaryView::GetAllFieldsReferenced(BinaryNinja::QualifiedName const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNGetAllSizesReferenced", referenced from:
      BinaryNinja::BinaryView::GetAllSizesReferenced(BinaryNinja::QualifiedName const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNGetAllTypesReferenced", referenced from:
      BinaryNinja::BinaryView::GetAllTypesReferenced(BinaryNinja::QualifiedName const&) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNGetBasicBlockInstructionContainingAddress", referenced from:
      BinaryNinja::BasicBlock::GetInstructionContainingAddress(unsigned long long, unsigned long long*) in libbinaryninjaapi.a(basicblock.cpp.o)
  "_BNGetFunctionAddressRanges", referenced from:
      BinaryNinja::Function::GetAddressRanges() in libbinaryninjaapi.a(function.cpp.o)
  "_BNGetFunctionHighestAddress", referenced from:
      BinaryNinja::Function::GetHighestAddress() in libbinaryninjaapi.a(function.cpp.o)
  "_BNGetFunctionLowestAddress", referenced from:
      BinaryNinja::Function::GetLowestAddress() in libbinaryninjaapi.a(function.cpp.o)
  "_BNGetInstructionContainingAddress", referenced from:
      BinaryNinja::Function::GetInstructionContainingAddress(BinaryNinja::Architecture*, unsigned long long, unsigned long long*) in libbinaryninjaapi.a(function.cpp.o)
  "_BNGetSizesReferenced", referenced from:
      BinaryNinja::BinaryView::GetSizesReferenced(BinaryNinja::QualifiedName const&, unsigned long long) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNGetTypesReferenced", referenced from:
      BinaryNinja::BinaryView::GetTypesReferenced(BinaryNinja::QualifiedName const&, unsigned long long) in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNHasInitialAnalysis", referenced from:
      BinaryNinja::BinaryView::HasInitialAnalysis() in libbinaryninjaapi.a(binaryview.cpp.o)
  "_BNSetAnalysisHold", referenced from:
      BinaryNinja::BinaryView::SetAnalysisHold(bool) in libbinaryninjaapi.a(binaryview.cpp.o)
ld: symbol(s) not found for architecture x86_64

**Comment by cfircohen** [comment]
Thanks for raising the issue. I recently tested the plugin on v3.5. Please reopen if you're still seeing issues.
